[package]
name = "ucas-proposal"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["YiQi Yao <@YaQia>", "Wenjie Xu <@WayneXuCN>"]
# Note: MIT license applies to the template code only.
# UCAS logos in assets/vi/ are copyrighted by UCAS and not covered by this license.
# See LOGO_COPYRIGHT.md for details.
license = "MIT"
description = "Master's or doctoral proposal/interim at the University of Chinese Academy of Sciences."
repository = "https://github.com/WayneXuCN/modern-ucas-thesis"
keywords = [
    "University of Chinese Academy of Sciences",
    "UCAS",
    "proposal",
    "interim",
    "dissertation",
    "typst",
    "template",
]
categories = ["thesis"]
exclude = ["imgs"]

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"
